services:
  web:
    build: .
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 8001:27017
    volumes:
      - mongo-data:/data/db
    command: mongod
volumes:
  mongo-data:
